### PR TITLE
Add ability to always associate to OS

### PR DESCRIPTION
**Pull request by sathieu**
with associate=always

### CODE REVIEW

**Comment by sathieu** [comment]
@GregSutcliffe @domcleal @fraenki: Can anyone review my PR?

**Comment by GregSutcliffe** [comment]
@sathieu had a brief read through, looks good, thanks! I'm about to merge something else that may conflict, but only slightly. You'll also need to add some tests to show that the new parameter works - we can help with that if needed :)

**Comment by GregSutcliffe** [comment]
@sathieu could you review #12 which is this with a rebase+tests? Thanks!

**Comment by sathieu** [comment]
superseeded by #12

**Comment by GregSutcliffe** [comment]
Merged as 338b16178d2ef07cf17484da3ab05677d44a6de0 - thanks!

**Pull request closed without merging**
