### PR TITLE
refs #3157 - rails 4 changes

### PR DESCRIPTION
**Pull request by unorthodoxgeek**
related to theforeman/foreman#2870

### CODE REVIEW

**Comment by mmoll** [comment]
:+1: this seems also to work at least with Foreman 1.10, so IMHO it would make sense to merge this and do a 2.0.2 release. @GregSutcliffe, what do you think?

**Comment by GregSutcliffe** [comment]
:+1: I'll merge tomorrow night if no one beats me to it ;)

**Comment by ekohl** [comment]
Thanks!

**Comment by GregSutcliffe** [comment]
Thanks guys - bumped to 2.0.2 in 7829ac8, sending packaging updates now.

**Pull request merged**
