### PR TITLE
Ignore vim modeline on the first line

### PR DESCRIPTION
**Pull request by lzap**
SSIA

```
$ ruby -e "puts STDIN.read.match(/<%\#\s?vim:\s?[a-z0-9=:]*(.+?).-?%>/m)[1]"
<%# vim:sw=2:ts=2:et
kind: snippet
name: kickstart_cmdline
-%>

kind: snippet
name: kickstart_cmdline
```

### CODE REVIEW

**Comment by lzap** [comment]
Wait, the regep's incorrect.

**Comment by lzap** [comment]
Fixed, should accept Emacs modeline as well.

**Comment by GregSutcliffe** [comment]
Thanks @lzap. The code's about to move once #27 is merged, so I'll evaluate this after that's reviewed/merged

**Comment by GregSutcliffe** [comment]
Refactored for #27 and merged (with a test) as 36ec033. Thanks @lzap and @orabin!

**Pull request closed without merging**
