### PR TITLE
Fixes #19294 - support templates from any context

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
[test]

**Comment by GregSutcliffe** [comment]
Seems to work, ACK pending tests.

**Comment by ares** [comment]
Test failures unrelated, not introduced by plugin, fixed by https://github.com/theforeman/foreman_templates/pull/48

**Comment by GregSutcliffe** [comment]
[test]

**Comment by ares** [comment]
[test]

**Comment by ares** [comment]
@GregSutcliffe tests are green, 4.0.2 released so I think this can get in

**Comment by GregSutcliffe** [comment]
Done, thanks @ares and @adamruzicka!

**Pull request merged**
