### PR TITLE
Add support for syncing job templates

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by stbenjam** [comment]
Can be tested with:

```
rake templates:sync repo="http://github.com/stbenjam/job_templates_sync_test" prefix="Steve " verbose=true
```

We'll also have a tool that lets users easily export/share their templates back to community-templates repo once https://github.com/theforeman/foreman_remote_execution/pull/165 is merged.

**Comment by stbenjam** [comment]
[test]

**Comment by ares** [comment]
Tested with community templates repo and it works great! @GregSutcliffe or any other maintainer, would you mind looking at this PR and merging? I'd say it also deserves version bump.

**Comment by GregSutcliffe** [comment]
Merged as 4905e884e47f14c7d872d3a6bda5449da9ed1318 and bumped to 2.1.0 (since this is new functionality). Sorry for the delay, and thanks @stbenjam and @ares!

**Comment by stbenjam** [comment]
Thanks @GregSutcliffe !

**Comment by GregSutcliffe** [comment]
Packaging at https://github.com/theforeman/foreman-packaging/pull/1138 and https://github.com/theforeman/foreman-packaging/pull/1139

**Pull request closed without merging**
