### PR TITLE
Rebase #10 and add tests

### PR DESCRIPTION
**Pull request by GregSutcliffe**
@mmoll This replaces #10 - it's a rebase of the original commit against latest HEAD (due to small conflicts) and some tests. Can you review?

@sathieu I hope you don't mind me adding the tests to your original code - they turned out to be quite messy, so I thought I'd just get it done ;)

### CODE REVIEW

**Comment by sathieu** [comment]
@GregSutcliffe of course not ;-)

Thanks for your improved version.

**Comment by mmoll** [comment]
Looking fine to me and also working in my light tests. :+1:

**Comment by GregSutcliffe** [comment]
Megred as 338b16178d2ef07cf17484da3ab05677d44a6de0 and a96b05651a927ef9fd341c7241640a09d0f4fb98 - thanks @sathieu for the feature!

**Comment by sathieu** [comment]
@GregSutcliffe thanks for the testsuite and merge!

**Pull request closed without merging**
