### PR TITLE
Support locking imported templates

### PR DESCRIPTION
**Pull request by treydock**
This would allow the behavior of this plugin to more closely mimic what's done by Foreman when it seeds in the community-templates repo.

### CODE REVIEW

**Comment by xprazak2** [comment]
Hi, thanks for your patch. It works nicely, but there is a slight discrepancy between API and rake task.

1) create a git repo with 2 branches, make some changes between branches
2) import templates via rake task, in my case:
```
bin/rake templates:import repo=https://github.com/xprazak2/fake_templates.git branch=new-branch verbose=true lock=true force=false
```
result: it imports the templates and locks them

3) try importing from other branch:
```
bin/rake templates:import repo=https://github.com/xprazak2/fake_templates.git branch=develop verbose=true lock=true force=false
```
the templates get updated. I would expect them not to since they are locked and `force` is `false`.
If I do the same workflow through API, the locked templates are not updated.

Could you add the lock option into readme, please?

**Comment by treydock** [comment]
@xprazak2 I'm not sure why the rake task would still be importing even when templates are locked.

My change does not yet handle snippets correctly, so this PR is likely incomplete.

I've updated the README.

**Comment by treydock** [comment]
Updated so that lock is set for snippets but if a snippet's content does not differ but locking differs, the lock won't be applied.  Let me know if the snippet logic should be improved.

**Comment by xprazak2** [comment]
I found out the cause why locked templates get unlocked via rake task and not via API. The culprit is the [`Template#locked?`](https://github.com/theforeman/foreman/blob/develop/app/models/template.rb#L26-L28) method. Easy fix is to replace it with just `locked` when importing.

Snippets should behave the same as other templates.

**Comment by treydock** [comment]
@xprazak2 Changes made, snippets now behave like other template types and using `Template#locked` instead of `Template#locked?`.

**Comment by xprazak2** [comment]
[test]

**Comment by xprazak2** [comment]
Everything works fine now, I squashed the commits and merged as 3d7c198, thanks!

**Pull request closed without merging**
