### PR TITLE
Fixed unit test

### PR DESCRIPTION
**Pull request by lzap**
It's failing for me, not sure what is wrong.

### CODE REVIEW

**Comment by ares** [comment]
does that happen when you run tests locally? jenkins does not seem to reproduce it

**Comment by lzap** [comment]
Yes, I only have discovery, bootdisk and templates enabled.

```
FactoryGirl.create(:ptable).model_name.human
=> "Partition Table"
```

To be honest I am unable to tell which is correct as this is STI.

**Comment by lzap** [comment]
Tests still fail for me locally without this patch.

**Comment by ares** [comment]
this patch would break tests running in jenkins, is there a chance, other plugin somehow touches the parth? did grep find something?

**Comment by lzap** [comment]
Anything hits your eye here?

```
 cat bundler.d/Gemfile.local.rb 
gem "facter"
gem "pry-rails"
#gem "pry-plus"
#gem "pry-coolline"
#gem "zeus"
gem "capybara-screenshot"
gem "benchmark-ips"

# plugins
#gem 'foreman_setup', :path => "../foreman_setup/"
gem 'foreman_bootdisk', :path => "../foreman_bootdisk/"
gem 'foreman_discovery', :path => "../foreman_discovery/"
#gem 'foreman_salt', :path => "../foreman_salt/"
#gem 'foreman_memcache', :path => "../foreman_memcache/"
gem 'foreman_templates', :path => "../foreman_templates/"
#gem 'foreman_default_hostgroup', :path => "../foreman_default_hostgroup/"
#gem 'foreman_hooks', :path => "../foreman_hooks/"
#gem 'foreman_abrt', :path => "../foreman_abrt/"
#gem 'foreman_remote_execution', :path => "../foreman_remote_execution/"
#gem 'foreman_name_generator', :path => '../foreman-name-generator'

#gem 'foreman_colly', :path => "../foreman_colly/"
#gem 'collectd-uxsock', :path => "../collectd-uxsock/"

# index checker
gem "lol_dba"
```

Maybe something with my test db? But it looks ok:

```
$ sqlite3 db/test.sqlite3 
SQLite version 3.19.3 2017-06-08 14:26:16
Enter ".help" for usage hints.
sqlite> .tables
architectures                          
architectures_operatingsystems         
audits                                 
auth_sources                           
bookmarks                              
cached_user_roles                      
cached_usergroup_members               
compute_attributes                     
compute_profiles                       
compute_resources                      
config_group_classes                   
config_groups                          
discovery_attribute_sets               
discovery_rules                        
domains                                
environment_classes                    
environments                           
external_usergroups                    
fact_names                             
fact_values                            
features                               
features_smart_proxies                 
filterings                             
filters                                
foreman_tasks_locks                    
foreman_tasks_recurring_logics         
foreman_tasks_task_group_members       
foreman_tasks_task_groups              
foreman_tasks_tasks                    
foreman_tasks_triggerings              
host_classes                           
host_config_groups                     
host_status                            
hostgroup_classes                      
hostgroups                             
hosts                                  
images                                 
key_pairs                              
locations_organizations                
logs                                   
lookup_keys                            
lookup_values                          
mail_notifications                     
media                                  
media_operatingsystems                 
messages                               
models                                 
module_test_facets                     
nics                                   
operatingsystems                       
operatingsystems_provisioning_templates
operatingsystems_ptables               
operatingsystems_puppetclasses         
os_default_templates                   
parameters                             
permissions                            
puppetclasses                          
realms                                 
reports                                
roles                                  
schema_migrations                      
sessions                               
settings                               
smart_proxies                          
sources                                
subnet_domains                         
subnets                                
taxable_taxonomies                     
taxonomies                             
template_combinations                  
template_kinds                         
templates                              
test_facets                            
tokens                                 
trend_counters                         
trends                                 
user_mail_notifications                
user_roles                             
usergroup_members                      
usergroups                             
users                                  
widgets   
```

**Comment by lzap** [comment]
How this resolves on your machine please?

    FactoryGirl.create(:ptable).model_name.human

**Comment by ares** [comment]
maybe it's caused by how you run tests, do you trigger them from core with the `rake test:foreman_templates`?

I'm getting this when I put pry in the test:
```
FactoryGirl.create(:ptable).model_name.human
=> "Ptable"
```

**Comment by lzap** [comment]
Ha! Nope, I do `rake test:discovery` but they execute as well for some reason I tried to fix but my PRs are pending for years.

**Comment by lzap** [comment]
Correction, I mitested. Deleted my previous comment, I can easily reproduce with:

```
[lzap@box foreman]$ rake test:foreman_templates
/home/lzap/.rbenv/versions/2.4.1/bin/ruby -I"lib:test:/home/lzap/work/foreman_templates/lib/tasks/../../test" -I"/home/lzap/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib" "/home/lzap/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb" "/home/lzap/work/foreman_templates/lib/tasks/../../test/functional/api/v2/template_controller_test.rb" "/home/lzap/work/foreman_templates/lib/tasks/../../test/unit/action_test.rb" "/home/lzap/work/foreman_templates/lib/tasks/../../test/unit/provisioning_template_test.rb" "/home/lzap/work/foreman_templates/lib/tasks/../../test/unit/ptable_test.rb" "/home/lzap/work/foreman_templates/lib/tasks/../../test/unit/template_exporter_test.rb" "/home/lzap/work/foreman_templates/lib/tasks/../../test/unit/template_importer_test.rb" 
-- SimpleCov coverage skipped, add simplecov to Gemfile.local to enable
The Apipie cache is turned off. Enable it and run apipie:cache rake task to speed up API calls.
Run options: --seed 36152

# Running:

................F..............................................................

Finished in 3.003893s, 26.2992 runs/s, 58.5906 assertions/s.

  1) Failure:
ForemanTemplates::TemplateExporterTest::#get_dump_dir#test_0003_does not appends anything for template without kind [/home/lzap/work/foreman_templates/test/unit/template_exporter_test.rb:73]:
--- expected
+++ actual
@@ -1 +1 @@
-"/tmp/ptables/"
+"/tmp/partition_tables_templates/"


79 runs, 176 assertions, 1 failures, 0 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -I"lib:test:/home/lzap/work/foreman_templates/lib/tasks/../../test" -I"/home/lzap/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib" "/home/lzap/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb" "/home/lzap/work/foreman_templates/lib/tasks/../../test/functional/api/v2/template_controller_test.rb" "/home/lzap/work/foreman_templates/lib/tasks/../../test/unit/action_test.rb" "/home/lzap/work/foreman_templates/lib/tasks/../../test/unit/provisioning_template_test.rb" "/home/lzap/work/foreman_templates/lib/tasks/../../test/unit/ptable_test.rb" "/home/lzap/work/foreman_templates/lib/tasks/../../test/unit/template_exporter_test.rb" "/home/lzap/work/foreman_templates/lib/tasks/../../test/unit/template_importer_test.rb" ]

Tasks: TOP => test:foreman_templates
(See full trace by running task with --trace)
```

**Comment by ares** [comment]
I'm closing this as no one else (including Mr. Jenkins) was able to reproduce this. Please reopen if you can reproduce in jenkins or create a reproducing environment.

**Pull request closed without merging**
