### PR TITLE
Fixes #21526 - start using factory bot

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by xprazak2** [comment]
👍

**Comment by ares** [comment]
of course, master tests are now failing with `uninitialized constant FactoryGirl (NameError)`, @xprazak2 could you please run tests manually on your setup and let us know how it goes?

**Comment by ares** [comment]
output on my end

```
...............................................................................

Finished in 3.960245s, 19.9483 runs/s, 44.4417 assertions/s.
79 runs, 176 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by xprazak2** [comment]
I got the same results, all passed.

**Comment by ares** [comment]
@GregSutcliffe  could you please merge? I'd also suggest giving Ondra merge permissions. He's demonstrated contribution through code and review on many occasions.

**Comment by xprazak2** [comment]
I already have merge permissions here, merging. Thanks!

**Comment by GregSutcliffe** [comment]
@xprazak2 thanks :)

**Comment by ares** [comment]
oh that's great, I forgot :-) thanks @xprazak2, I see there are still two offenses so we'll need to update rubocop in separate PR

**Pull request merged**
