### PR TITLE
Rename ConfigTemplate to ProvisioningTemplate

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by mmoll** [comment]
This is not going to work with Foreman 1.8, correct?

**Comment by ares** [comment]
correct

**Comment by domcleal** [comment]
PR tests are now running properly here, which is showing it's trying to use a config_templates factory, can you change that please?

I also just broke the tests by causing the main job to run, so you'll need to retrigger http://ci.theforeman.org/job/test_plugin_pull_request/888/ manually once updated, sorry!

**Comment by domcleal** [comment]
@mmoll I suggest we bump the version to 2.0.0?

**Comment by mmoll** [comment]
exactly.

**Comment by ares** [comment]
Manually triggered http://ci.theforeman.org/job/test_plugin_pull_request/889/

**Comment by domcleal** [comment]
@ares it looks red still

**Comment by ares** [comment]
That was because of my typo in @pt (vs @tp), killed old and triggered a new run - http://ci.theforeman.org/job/test_plugin_pull_request/892/

**Comment by domcleal** [comment]
Thanks @ares!

**Pull request merged**
