### PR TITLE
Fixes #28394 - Make dirname visible in UI for syncs

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by adamruzicka** [comment]
The test failures are odd

[test foreman_templates]

**Comment by xprazak2** [comment]
[test foreman_templates]

**Comment by xprazak2** [comment]
[test foreman_templates]

**Comment by tbrisker** [comment]
Test failures indeed unrelated, this is a transient failure we've been seeing for a while.

**Comment by ares** [comment]
Thanks @xprazak2 and @adamruzicka, merging!

**Pull request merged**
