### PR TITLE
update @theforeman js to v10

### PR DESCRIPTION
**Pull request by MariaAga**

### CODE REVIEW

**Comment by adamruzicka** [comment]
`@theforeman/*` v10 is Foreman 3.3 and higher?

**Comment by MariaAga** [comment]
v10.0.0 is in 3.2 and v10.1.0 I think will be in 3.3

**Comment by adamruzicka** [comment]
Could you bump the version in engine.rb please?

**Comment by MariaAga** [comment]
Updated

**Comment by ofedoren** [comment]
Thanks, @MariaAga, @adamruzicka!

**Pull request merged**
