### PR TITLE
Fixes #22352 - Do not trim whitespace for prefix setting

### PR DESCRIPTION
**Pull request by xprazak2**
needs a change in [core](https://github.com/theforeman/foreman/pull/5198) to work

### CODE REVIEW

**Comment by ares** [comment]
@xprazak2  could you please rebase?

**Comment by xprazak2** [comment]
Rebased

**Comment by ares** [comment]
Lgtm, @jyejare, mind to test it fixes the issue?

**Comment by ares** [comment]
Thanks @xprazak2, fixes the problem, merging

**Pull request merged**
